//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracaDyplomowaBackend.Utilities.GlobalMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PracaDyplomowaBackend.Utilities.GlobalMessages.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor nie posiada danego gatunku..
        /// </summary>
        public static string AuthorGenreNotFound {
            get {
                return ResourceManager.GetString("AuthorGenreNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor nie został znaleziony w bazie danych..
        /// </summary>
        public static string AuthorNotFound {
            get {
                return ResourceManager.GetString("AuthorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednego lub więcej autorów nie znaleziono w bazie danych..
        /// </summary>
        public static string AuthorsNotFound {
            get {
                return ResourceManager.GetString("AuthorsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Książka nie posiada takiego autora..
        /// </summary>
        public static string BookAuthorNotFound {
            get {
                return ResourceManager.GetString("BookAuthorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Książka nie posiada danego gatunku..
        /// </summary>
        public static string BookGenreNotFound {
            get {
                return ResourceManager.GetString("BookGenreNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Książka nie została znaleziona w bazie danych..
        /// </summary>
        public static string BookNotFound {
            get {
                return ResourceManager.GetString("BookNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recenzja nie została znaleziona w bazie danych..
        /// </summary>
        public static string BookReviewNotFound {
            get {
                return ResourceManager.GetString("BookReviewNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentarz nie został znaleziony w bazie danych..
        /// </summary>
        public static string CommentNotFound {
            get {
                return ResourceManager.GetString("CommentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik nie posiada tej książki wśród listy aktualnie czytanych książek..
        /// </summary>
        public static string CurrentlyReadBookNotFound {
            get {
                return ResourceManager.GetString("CurrentlyReadBookNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik nie posiada tego autora wśród listy swoich ulubionych..
        /// </summary>
        public static string FavoriteAuthorNotFound {
            get {
                return ResourceManager.GetString("FavoriteAuthorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik nie posiada tej książki wśród listy swoich ulubionych..
        /// </summary>
        public static string FavoriteBookNotFound {
            get {
                return ResourceManager.GetString("FavoriteBookNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gatunek nie został znaleziony w bazie danych..
        /// </summary>
        public static string GenreNotFound {
            get {
                return ResourceManager.GetString("GenreNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednego lub więcej gatunków nie znaleziono w bazie danych..
        /// </summary>
        public static string GenresNotFound {
            get {
                return ResourceManager.GetString("GenresNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obraz nie został znaleziony w bazie danych..
        /// </summary>
        public static string ImageNotFound {
            get {
                return ResourceManager.GetString("ImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podane hasło jest niepoprawne..
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik jest pusty..
        /// </summary>
        public static string NullFile {
            get {
                return ResourceManager.GetString("NullFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocena nie została znaleziona w bazie danych..
        /// </summary>
        public static string RateNotFound {
            get {
                return ResourceManager.GetString("RateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik nie posiada tej książki wśród listy przeczytanych książek..
        /// </summary>
        public static string ReadBookNotFound {
            get {
                return ResourceManager.GetString("ReadBookNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rola nie została znaleziona w bazie danych..
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił błąd podczas zapisu..
        /// </summary>
        public static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik nie został znaleziony w bazie danych..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik nie posiada tej książki wśród listy pożądanych książek..
        /// </summary>
        public static string WantedBookNotFound {
            get {
                return ResourceManager.GetString("WantedBookNotFound", resourceCulture);
            }
        }
    }
}
